import Link from "next/link";

import { CTASection } from "@/components/CTASection";
import { buildMetadata } from "@/lib/seo";
import { getPublishedPosts } from "@/lib/posts";

export const metadata = buildMetadata({
  title: "Shopify Hydrogen Blog for Store Owners | Emre Mutlu",
  description:
    "Merchant-focused Shopify Hydrogen articles covering cost, speed, migration fit, and launch planning in plain English for store owners today.",
  path: "/blog",
});

interface BlogPageProps {
  searchParams: Promise<{ page?: string }>;
}

export default async function BlogPage({ searchParams }: BlogPageProps) {
  const params = await searchParams;
  const currentPage = Math.max(1, Number.parseInt(params.page ?? "1", 10) || 1);
  const posts = await getPublishedPosts();
  const postsPerPage = 10;
  const totalPages = Math.max(1, Math.ceil(posts.length / postsPerPage));
  const clampedPage = Math.min(currentPage, totalPages);
  const startIndex = (clampedPage - 1) * postsPerPage;
  const pagePosts = posts.slice(startIndex, startIndex + postsPerPage);

  return (
    <div className="page-shell">
      <section className="max-w-4xl space-y-6">
        <p className="eyebrow">Blog</p>
        <h1 className="font-display text-5xl leading-tight text-slate-900 md:text-6xl">
          Shopify Hydrogen guidance for store owners
        </h1>
        <p className="text-xl leading-9 text-slate-600">
          No code. No jargon-heavy architecture lectures. Just practical answers
          to the questions store owners actually Google before a Hydrogen
          project.
        </p>
      </section>

      <section className="grid gap-6">
        {pagePosts.length > 0 ? (
          pagePosts.map((post) => (
            <article key={post.slug} className="card">
              <p className="text-sm font-semibold uppercase tracking-[0.16em] text-blue-600">
                {post.publishedAt
                  ? new Date(post.publishedAt).toLocaleDateString("en-US", {
                      month: "long",
                      day: "numeric",
                      year: "numeric",
                    })
                  : "Coming soon"}
              </p>
              <h2 className="mt-4 text-3xl font-semibold text-slate-900">
                <Link href={`/blog/${post.slug}`} className="transition hover:text-blue-600">
                  {post.title}
                </Link>
              </h2>
              <p className="mt-4 text-base leading-8 text-slate-600">
                {post.metaDescription}
              </p>
              <Link
                href={`/blog/${post.slug}`}
                className="mt-6 inline-flex text-sm font-semibold text-blue-600 transition hover:text-blue-700"
              >
                Read article
              </Link>
            </article>
          ))
        ) : (
          <div className="card">
            <h2 className="text-2xl font-semibold text-slate-900">
              Fresh posts will appear here automatically
            </h2>
            <p className="mt-4 text-base leading-8 text-slate-600">
              Once Supabase is connected, merchant-focused articles generated by
              the scheduled publishing workflow will show up here.
            </p>
          </div>
        )}
      </section>

      <section className="flex items-center justify-between gap-4 rounded-[1.5rem] border border-slate-200 bg-white px-6 py-5">
        <p className="text-sm font-medium text-slate-600">
          Page {clampedPage} of {totalPages}
        </p>
        <div className="flex gap-3">
          {clampedPage > 1 ? (
            <Link
              href={`/blog?page=${clampedPage - 1}`}
              className="rounded-full border border-slate-300 px-4 py-2 text-sm font-semibold text-slate-700"
            >
              Previous
            </Link>
          ) : null}
          {clampedPage < totalPages ? (
            <Link
              href={`/blog?page=${clampedPage + 1}`}
              className="rounded-full bg-blue-600 px-4 py-2 text-sm font-semibold text-white"
            >
              Next
            </Link>
          ) : null}
        </div>
      </section>

      <CTASection
        primaryLink="linkedin"
        subtext="If an article sounds close to your situation, send me the link and I’ll tell you what it would look like for your store specifically."
      />
    </div>
  );
}
