export const BRAND_CLIENT_ASSETS = {
  eveshop: {
    id: "eveshop",
    name: "EveShop",
    logoSrc: "/brand/case-studies/eveshop-logo.png",
    logoAlt: "EveShop logo",
    previewMode: "image" as const,
    previewMetric: "400K+",
    previewSubLabel: "users",
    previewTheme: "bg-[linear-gradient(180deg,#202124_0%,#111111_100%)]",
    imageSrc: "/brand/case-studies/eveshop-storefront.png",
    imageAlt: "EveShop live storefront screenshot showing cosmetics and personal care ecommerce navigation.",
  },
  bayam: {
    id: "bayam",
    name: "Bayam Jewelry",
    logoSrc: "/brand/case-studies/bayam-logo.svg",
    logoAlt: "Bayam Jewelry logo",
    previewMode: "logo-panel" as const,
    previewMetric: "2 Worlds",
    previewTheme: "bg-black",
    imageSrc: "/brand/case-studies/bayam-storefront.png",
    imageAlt: "Bayam Jewelry live storefront screenshot showing luxury jewelry and watch shopping context.",
  },
  rebelBunny: {
    id: "rebel-bunny",
    name: "Rebel Bunny Matcha",
    logoSrc: "/brand/case-studies/rebel-bunny-logo.png",
    logoAlt: "Rebel Bunny Matcha logo",
    previewMode: "image" as const,
    previewTheme: "bg-[#d7f0de]",
    imageSrc: "/brand/case-studies/rebel-bunny-storefront.png",
    imageAlt: "Rebel Bunny Matcha live storefront screenshot showing DTC matcha product storytelling.",
  },
  kirazev: {
    id: "kirazev",
    name: "Kirazev",
    logoAlt: "Kirazev case study label",
    previewMode: "image" as const,
    previewMetric: "Liquid",
    previewSubLabel: "home goods catalog",
    previewTheme: "bg-[#173a33]",
    imageSrc: "/brand/case-studies/kirazev-storefront.png",
    imageAlt: "Kirazev live storefront screenshot showing home goods catalog navigation.",
  },
  clohi: {
    id: "clohi",
    name: "Clohi",
    logoAlt: "Clohi case study label",
    previewMode: "image" as const,
    previewMetric: "India",
    previewSubLabel: "apparel Liquid build",
    previewTheme: "bg-[#432145]",
    imageSrc: "/brand/case-studies/clohi-storefront.png",
    imageAlt: "Clohi live storefront screenshot showing India-focused apparel shopping context.",
  },
} as const;

export type BrandClientId = (typeof BRAND_CLIENT_ASSETS)[keyof typeof BRAND_CLIENT_ASSETS]["id"];

export const SELECTED_WORK_ITEMS = [
  {
    id: "eveshop",
    href: "/case-studies/eveshop-shopify-hydrogen",
    title: "EveShop",
    eyebrow: "Nationwide cosmetics retailer — Turkey",
    body: "Frontend team lead on Turkey's first production Shopify Hydrogen storefront.",
    mediaLabel: "Nationwide retail",
    mediaMode: "image" as const,
  },
  {
    id: "bayam",
    href: "/case-studies/bayam-jewelry-shopify-hydrogen",
    title: "Bayam Jewelry",
    eyebrow: "Fine jewelry and luxury watches — New York",
    body: "Hydrogen storefront for a two-world luxury catalog running on a dedicated commerce subdomain.",
    mediaLabel: "Luxury ecommerce",
    mediaMode: "image" as const,
  },
  {
    id: "rebel-bunny",
    href: "/case-studies/rebel-bunny-shopify-hydrogen",
    title: "Rebel Bunny Matcha",
    eyebrow: "Premium matcha — DTC and wholesale",
    body: "Dual-funnel storefront serving both direct-to-consumer buyers and wholesale partners.",
    mediaLabel: "Social-first DTC",
    mediaMode: "image" as const,
  },
  {
    id: "kirazev",
    href: "/case-studies/kirazev-shopify-liquid",
    title: "Kirazev",
    eyebrow: "Home goods catalog — Shopify Liquid",
    body: "Fast Liquid build for kitchen, decor, bathroom, and organizer product discovery.",
    mediaLabel: "Home goods",
    mediaMode: "image" as const,
  },
  {
    id: "clohi",
    href: "/case-studies/clohi-shopify-liquid",
    title: "Clohi",
    eyebrow: "International apparel — Shopify Liquid",
    body: "India-focused apparel storefront for ethnic, casual, and festive wear buying behavior.",
    mediaLabel: "Apparel",
    mediaMode: "image" as const,
  },
] as const;
